[FIX] Fix circular import in config and implement cached config
```
> otools-project --help

ImportError: cannot import name 'get_conf_key' from partially initialized module 'odoo_tools.config' (most likely due to a circular import)
```